### PR TITLE
Add profiling for the redraw loop in debug mode

### PR DESCRIPTION
**Pull request by ensonic**

### CODE REVIEW

**Comment by dlech** [comment]
The high priority idle commit is good.

I'm not sure how I feel about the profiling though. It makes the code a bit messy (harder to read) and it is not something that I am likely to use myself.

**Comment by ensonic** [comment]
Yes, the ifdefs are ugly. I'll see if I can make that a bit prettier.

**Comment by dlech** [comment]
Maybe have 2 versions of the function with a single ifdef. It's a bit of duplicated code, but much easier to read. Also, I'm not a fan of the double negative (`#if ! NDEBUG`). I would much rather have a `DEBUG` than `NDEBUG`.

**Comment by dlech** [comment]
Also, since the output is rather verbose, I don't want this tied to the CMAKE_BUILD_TYPE. Can we use cmake's `option` function instead and give it its own variable to turn in on and off? I want to make sure it is turned off unless we really need it.

**Comment by ensonic** [comment]
Regarding the `#if ! NDEBUG`, I agree, but that is what you already use. I can see what I can learn about cmakes option function. I never used cmake before. But if this is getting to complicated, I just drop the 2nd patch. It was not too much work to add.
Regarding the verbosity, it is only logged when you enable the debug level, which is off by default. So it needs a special build + an env var setting.

**Comment by dlech** [comment]
I don't particularly see a need for the 2nd patch now that we are running better, so dropping it is fine. I always use `CMAKE_BUILD_TYPE=Debug` when developing. That is what enables the `-g` in `CFLAGS`.

And you have me curious, where is `#if ! NDEBUG` already? If I did do that, it was quite a while back.

**Comment by ensonic** [comment]
if you run ccmake ../ev3devkit and then press 't' you see the defaults for the various build type. Looks like this is a cmake default, so it is not you to blame. It would be too nice, if a build system would not have some weirdness :)

**Comment by ensonic** [comment]
I added an option and defined 3 internal helpers. Since vala is creating static functions for those, the compiler will be able to inline and also eliminate them if empty. This reduces the #if clutter. Still if you don't like them I can drop this (or keep it as a local patch).

**Comment by dlech** [comment]
That looks better. If this is something you think will be useful in the long term, I'll take it.

**Comment by ensonic** [comment]
What I am thinking is to check wheter the whole redraw took more that the reserved timeslice and only log the values in that case. Then I can use it on the device and check the log from time to time (e.g. after some workshop).

**Comment by ensonic** [comment]
Can you cherry pick the ones without the redraw loop? Otherwise I drop this PR, send the patch 1,3 as a new PR and then keep patch 2 local.

**Comment by dlech** [comment]
done.

**Pull request closed without merging**
